name: "CD"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        env:
          REPOSRC: "$GITHUB_SERVER_URL/${GITHUB_REPOSITORY}.git"
          LOCALREPO: "${{ secrets.LOCALREPO }}"
          LOCALREPO_VC_DIR: "$LOCALREPO/.git"
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          envs: REPOSRC,LOCALREPO,LOCALREPO_VC_DIR
          script: |
            if [ ! -d $LOCALREPO_VC_DIR ]
            then
                git clone $REPOSRC $LOCALREPO
            else
                cd $LOCALREPO
                git checkout -f
                git pull
            fi
