name: "CD"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        env:
          REPOSRC: ${{ github.server_url }}/${{ github.repository }}.git
          LOCALREPO: ${{ secrets.LOCALREPO }}
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          envs: REPOSRC,LOCALREPO
          script: |
            if [ ! -d $LOCALREPO ]
            then
                git clone $REPOSRC $LOCALREPO
            else
                cd $LOCALREPO
                git checkout -f
                git pull
            fi
